var c=document.getElementById("trigon");
var ctx=c.getContext("2d");
ctx.moveTo(0,0);
ctx.lineTo(50,50);
ctx.moveTo(50,50);
ctx.lineTo(100,0);
ctx.moveTo(100,0);
ctx.lineTo(0,0);
ctx.strokeStyle="green";
ctx.stroke();
